#!/usr/bin/env sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Mechanically import only the 32 new GPL holiday emblems from the PS1 sheet.

set -eu

project_root=$(CDPATH='' cd -- "$(dirname "$0")/.." && pwd)
source_asset=${1:-}
output="$project_root/src/jc_holiday_emblems.inc"
expected_sheet=e44b00840a6408037fa01a118b03fbc0a976274871126b3421eb3a6bcd0cc9ec
expected_payload=59c9c3d2c4cb5c94684e3c5f7b5d90562aa18285d74bd786044a8d7ce54ce2db
original_prefix_bytes=8892

if [ -z "$source_asset" ] || [ ! -f "$source_asset" ]; then
    printf 'usage: %s /path/to/PS1/jc_resources/extracted/bmp/HOLIDAY.BMP\n' "$0" >&2
    exit 2
fi
if [ "$(sha256sum "$source_asset" | awk '{print $1}')" != "$expected_sheet" ]; then
    printf 'error: HOLIDAY.BMP does not match the pinned GPL PS1 sheet\n' >&2
    exit 1
fi

temporary=$(mktemp -d)
trap 'rm -rf "$temporary"' EXIT HUP INT TERM
payload="$temporary/new-emblems.bin"
tail -c "+$((original_prefix_bytes + 1))" "$source_asset" >"$payload"
if [ "$(wc -c <"$payload" | tr -d ' ')" != 16384 ] ||
   [ "$(sha256sum "$payload" | awk '{print $1}')" != "$expected_payload" ]; then
    printf 'error: extracted new-emblem payload is not exact\n' >&2
    exit 1
fi

{
    printf '%s\n' '/* SPDX-License-Identifier: GPL-3.0-or-later */'
    printf '%s\n' '/* Mechanically generated by scripts/import-holiday-emblems.sh. */'
    printf '%s\n' '/* PS1 sheet e44b0084...; new-art payload 59c9c3d2... */'
    printf '%s\n' 'static const unsigned char jc_holiday_emblem_packed[16384] = {'
    xxd -i <"$payload"
    printf '%s\n' '};'
} >"$output"
printf 'wrote %s (32 GPL-generated 32x32 emblems; original four excluded)\n' "$output"
